const express=require('express');
const {load,save}=require('../services/store');
const {getLevel}=require('../services/levels');
const router=express.Router();
function auth(req,res,next){const db=load(); const pass=process.env.ADMIN_PASSWORD||db.settings.adminPassword; if(req.query.pass===pass || req.body.pass===pass) return next(); res.send(`<h2>🍌 後台登入</h2><form method="get"><input name="pass" type="password" placeholder="密碼"><button>登入</button></form>`);}
router.get('/',auth,(req,res)=>{const db=load(); const users=Object.values(db.users); res.send(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:sans-serif;background:#fff8d6;padding:16px}a,button{display:inline-block;margin:6px;padding:10px;background:#ffcf33;border-radius:10px;color:#222;text-decoration:none;border:0}.card{background:white;padding:14px;border-radius:14px;margin:10px 0}</style><h1>🍌 Banana Friends 後台</h1><div class=card>會員 ${users.length}｜管理員 ${db.admins.length}｜黑名單 ${Object.keys(db.blacklist).length}</div><a href="/admin/users?pass=${req.query.pass}">會員</a><a href="/admin/settings?pass=${req.query.pass}">設定</a><a href="/admin/shop?pass=${req.query.pass}">商店</a><a href="/admin/pokemon?pass=${req.query.pass}">Pokemon GO</a><a href="/admin/logs?pass=${req.query.pass}">紀錄</a>`);});
router.get('/users',auth,(req,res)=>{const db=load(); const rows=Object.values(db.users).sort((a,b)=>b.exp-a.exp).map(u=>`<tr><td>${u.name}</td><td>Lv.${getLevel(u.exp)}</td><td>${u.exp}</td><td>${u.coins}</td><td>${u.chatCount||0}</td></tr>`).join(''); res.send(`<h2>會員</h2><table border=1 cellpadding=6><tr><th>名稱</th><th>等級</th><th>EXP</th><th>幣</th><th>聊天</th></tr>${rows}</table>`);});
router.get('/settings',auth,(req,res)=>{const db=load(); res.send(`<h2>設定</h2><form method=post><input type=hidden name=pass value="${req.query.pass}">每日EXP<input name=dailyExp value="${db.settings.dailyExp}"><br>每日幣<input name=dailyCoins value="${db.settings.dailyCoins}"><br>聊天EXP<input name=chatExp value="${db.settings.chatExp}"><br>冷卻秒<input name=chatCooldownSec value="${db.settings.chatCooldownSec}"><br>群規<textarea name=groupRules rows=6 cols=40>${db.settings.groupRules}</textarea><br>歡迎<textarea name=welcome rows=4 cols=40>${db.settings.welcome}</textarea><br>預設徽章圖URL<input name=defaultBadgeUrl value="${db.settings.defaultBadgeUrl||''}" style="width:100%"><br><button>儲存</button></form>`);});
router.post('/settings',auth,(req,res)=>{const db=load(); Object.assign(db.settings, req.body); ['dailyExp','dailyCoins','chatExp','chatCooldownSec'].forEach(k=>db.settings[k]=Number(db.settings[k])); save(db); res.redirect('/admin?pass='+req.body.pass);});
router.get('/shop',auth,(req,res)=>{const db=load(); const rows=db.shop.map((i,n)=>`<li>${i.category}｜${i.name}｜${i.price} 幣｜${i.enabled!==false?'上架':'下架'}</li>`).join(''); res.send(`<h2>商店</h2><ul>${rows}</ul><form method=post><input type=hidden name=pass value="${req.query.pass}">分類<input name=category><br>名稱<input name=name><br>價格<input name=price><br><button>新增</button></form>`);});
router.post('/shop',auth,(req,res)=>{const db=load(); db.shop.push({category:req.body.category,name:req.body.name,price:Number(req.body.price)||0,enabled:true}); save(db); res.redirect('/admin/shop?pass='+req.body.pass);});
router.get('/pokemon',auth,(req,res)=>{const db=load(); res.send(`<h2>Pokemon GO</h2><form method=post><input type=hidden name=pass value="${req.query.pass}">社群日<textarea name=communityDay rows=4 cols=40>${db.pokemon.communityDay}</textarea><br>團體戰<textarea name=raids rows=4 cols=40>${db.pokemon.raids}</textarea><br>兌換碼<textarea name=codes rows=4 cols=40>${db.pokemon.codes}</textarea><br><button>儲存</button></form>`);});
router.post('/pokemon',auth,(req,res)=>{const db=load(); db.pokemon={communityDay:req.body.communityDay,raids:req.body.raids,codes:req.body.codes}; save(db); res.redirect('/admin/pokemon?pass='+req.body.pass);});
router.get('/logs',auth,(req,res)=>{const db=load(); res.send('<h2>紀錄</h2><pre>'+JSON.stringify(db.logs,null,2)+'</pre>');});
module.exports=router;
