const express=require('express');
const line=require('@line/bot-sdk');
const bodyParser=require('body-parser');
const admin=require('./routes/admin');
const {config,handleEvent}=require('./services/bot');
const app=express();
app.use('/admin', bodyParser.urlencoded({extended:true}), admin);
app.get('/',(req,res)=>res.send('🍌 Banana Friends Bot V8 is running'));
app.post('/webhook', line.middleware(config), async (req,res)=>{try{await Promise.all(req.body.events.map(handleEvent)); res.status(200).end();}catch(e){console.error(e); res.status(200).end();}});
const port=process.env.PORT||10000;
app.listen(port,()=>console.log(`🍌 Banana Friends Bot V8 running on port ${port}`));
